name: Cloud Run

on:
  push:
  workflow_dispatch:

concurrency: ${{ github.ref }}

env:
  IMAGE: us-docker.pkg.dev/lead-docket-connector/docker-1/vineskills-fb:${{ github.ref_name }}

  SERVICE: vineskills-fb-${{ github.ref_name }}
  PUBLIC_URL: https://vineskills-fb-${{ github.ref_name }}-lx3iji7qaq-uc.a.run.app

  REGION: us-central1
  GCP_SA: integration-1@lead-docket-connector.iam.gserviceaccount.com

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: google-github-actions/auth@v0
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - uses: docker/setup-buildx-action@v2
        with:
          install: true

      - uses: google-github-actions/setup-gcloud@v0

      - run: gcloud auth configure-docker us-docker.pkg.dev

      - uses: docker/build-push-action@v4
        with:
          push: true
          tags: ${{ env.IMAGE }}

      - run: >-
          gcloud run deploy ${{ env.SERVICE }}
          --image=${{ env.IMAGE }}
          --memory=8Gi
          --cpu=2
          --platform=managed
          --service-account=${{ env.GCP_SA }}
          --region=${{ env.REGION }}
          --timeout=3500
          --set-env-vars=PUBLIC_URL=${{ env.PUBLIC_URL }}
          --allow-unauthenticated

      - run: >-
          gcloud run services add-iam-policy-binding ${{ env.SERVICE }}
          --member="allUsers"
          --role="roles/run.invoker"
